export const RABBIT_HANDLER_TOKEN = Symbol('RABBIT_HANDLER_TOKEN');

export const RABBIT_MODULE_OPTIONS_TOKEN = Symbol('RABBIT_MODULE_OPTIONS_TOKEN');

export const RABBIT_MERGED_MODULE_OPTIONS_TOKEN = Symbol('RABBIT_MERGED_MODULE_OPTIONS_TOKEN');

export const AMQP_CONNECTION_MANAGER_TOKEN = Symbol('AMQP_CONNECTION_MANAGER_TOKEN');

export const RABBIT_CHANNEL_WRAPPERS_TOKEN = Symbol('RABBIT_CHANNEL_WRAPPERS_TOKEN');

export const RABBIT_DEFAULT_CHANNEL_WRAPPER_TOKEN = Symbol('RABBIT_DEFAULT_CHANNEL_WRAPPER_TOKEN');
